### ISSUE TITLE
unable to connect with server

### ISSUE THREAD

**Issue by TUWienAlex** [hitranonline/hapi2#4]
dear developer team,
i sucsessfully installed the hapi2 module but can´t get acess to the server. 
after inserting the following code and pasting the API-key (form my hapi account) I recieve the following error.  I don´t know what I did wrong. 

```
import json
from getpass import getpass

import pylab as pl
import matplotlib as mpl

from hapi2 import *

with open('config.json') as f:
    print(f.read())    
    
SETTINGS['api_key'] = getpass('Enter valid API key:')
fetch_info()
```

`<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>`

**Comment by RomanKochanov** [comment]
Hi TUWienAlex.

We were unable to reproduce this error. Which OS/Python distrivbution do you use?

**Comment by TUWienAlex** [comment]
I use Windows 10 (nt), Anaconda with Spyder Version 5.2.2 and Python Version- 3.9.13 
Thank you for your help!
